### ISSUE TITLE
"rem() takes 2 positional arguments but 3 were given" when using the correct body.

### ISSUE THREAD

**Issue by 52617365** [FooSoft/anki-connect#335] opened 2022-06-17 08:15 UTC
I'm making a Neovim plugin that lets you do the Anki stuff from inside of Neovim and I ran into a problem when trying to delete decks from Anki.

My post request body looks like this:

`{"version": 6, "action": "deleteDecks", "params": {"cardsToo": true, "decks": ["asd"]}}   `

The response looks like this:
`
{"result": null, "error": "rem() takes 2 positional arguments but 3 were given"} `

It seems to me that the body is indeed correct and that there is probably something wrong with the API itself. Also tried the same in curl and it did not work.

**Comment by oakkitten** [comment] 2022-06-21 17:38
A duplicate of #286, fixed in master. 

@FooSoft I think the version on AnkiWeb is outdated?

**Comment by FooSoft** [comment] 2022-07-03 18:44
@oakkitten so funny story. I'm still trying to figure out how the hell to update the plugin for a range of versions on AnkiWeb. I'm not seeing a way to make it so that specific versions of Anki get specific versions of the plugin :|

**Comment by FooSoft** [comment] 2022-07-14 20:14
Thanks @oakkitten , I finally got it working and pushed out a release of the latest and greatest.

**Closed** 2022-07-14 23:32 UTC
